// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9lpMCCKqkvF_BapvUpHJ_OhnPJlK5AJI',
    appId: '1:498164755389:web:263ca4059194df5d0a80d4',
    messagingSenderId: '498164755389',
    projectId: 'camal-2da42',
    authDomain: 'camal-2da42.firebaseapp.com',
    storageBucket: 'camal-2da42.appspot.com',
    measurementId: 'G-5MBWP8NVWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_nb79Y2J59N3eAyNIyjTejpvrj41arWo',
    appId: '1:498164755389:android:2b2c4e767d3f88250a80d4',
    messagingSenderId: '498164755389',
    projectId: 'camal-2da42',
    storageBucket: 'camal-2da42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzsalJc0HsikMkh-25nqd09JiXmk7ZMOI',
    appId: '1:498164755389:ios:8245b843351d49c00a80d4',
    messagingSenderId: '498164755389',
    projectId: 'camal-2da42',
    storageBucket: 'camal-2da42.appspot.com',
    iosBundleId: 'com.camal.iscocongacamal',
  );
}
